Update L2_Bridge_schema.graphql
hop-protocol/subgraph pull request #4
Opened 2022-09-13 17:53 UTC by PaulieB14

Added descriptions.  *Note: copied from L1.  If I missed any differences please let me know.  But they looked the exact same.

2022-09-17 23:24 UTC, miguelmota requested changes
Thanks for the entity descriptions. The L2 schema is not exactly the same as the L1 schema so copying the schema as is would cause undesired changes. Left some comments

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +type ChallengeResolved @entity {
This entity shouldn't exist in L2 schema

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +type TransferBondChallenged @entity {
This entity shouldn't exist in L2 schema

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +type TransferRootBonded @entity {
This entity shouldn't exist in L2 schema

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +type TransferRootConfirmed @entity {
This entity shouldn't exist in L2 schema

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type TransfersCommitted @entity {
This entity shouldn't be removed

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type BonderFee @entity {
This entity shouldn't be removed

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
>    tokenEntity: Token!
This entity property shouldn't exist

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +  tokenEntity: Token!
This entity property shouldn't exist

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type RemoveLiquidityImbalance @entity {
This entity shouldn't be removed

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type RemoveLiquidityOne @entity {
This entity shouldn't be removed

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type RemoveLiquidity @entity {
This entity shouldn't be removed

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type AddLiquidity @entity {
This entity shouldn't be removed

2022-09-17 23:24 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -type TransferSent @entity {
This entity shouldn't be removed

2022-09-19 03:00 UTC, PaulieB14 commented
@miguelmota. Sorry I thought L2 was the same.  I went back and started from scratch and added descriptions.  There were some entities that were missing descriptions that I added.  Let me know if revisions are needed.

2022-09-20 06:40 UTC, miguelmota requested changes
thanks @PaulieB14! see additional minor comments that need to be addressed and then it can be merged

2022-09-20 06:40 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +ƒ
there's a random artifact here

2022-09-20 06:40 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -  from: String!
looks like this got overridden by mistake and should be added

2022-09-20 06:40 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -  from: String!
looks like this got overridden by mistake and should be added

2022-09-20 06:40 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -  from: String!
looks like this got overridden by mistake and should be added

2022-09-20 06:40 UTC, miguelmota commented on L2_Bridge_schema.graphql
> -  from: String!
looks like this got overridden by mistake and should be added

2022-09-20 06:40 UTC, miguelmota commented on L2_Bridge_schema.graphql
> +
these trailing newlines should be removed

2022-09-20 12:19 UTC, PaulieB14 commented
@miguelmota Thanks for the revisions.  I think we are good to go now.

2022-09-20 17:05 UTC, merged

2022-09-20 17:05 UTC, miguelmota commented
@PaulieB14 looks good! merging